#! /bin/sh

### BEGIN INIT INFO
# Provides:             logcards
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    LogCards RFID Door Opener
### END INIT INFO

case "$1" in
  start)
        modprobe -r i2c_bcm2708
        modprobe i2c_bcm2708 baudrate=200000
        echo 25 > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio25/direction
        /usr/bin/screen -S rfid -d -m /home/pi/logcards/run_logcards.sh
        ;;
esac

exit 0
