# Some general settings
settings:
# Optional timezone, used for defining half-days of hotdesking
    timezone: "Europe/London"
# A hash of environments
# The key will be that value of DOORBOT_ENV
# The value is a hash consisting of:
#   loghotdesk:   If "yes" then hot desk use will be logged
#   access:       An array of access levels accepted by this door.
#                 If not present or empty, *any* access will open door.
#   kindle:       Information required for the kindle access
#       ip:       The address that the kindle is set to
#       user:     The user for the connection to the kindle
#       password: The password for that user
#       port:     The port the ssh server is running on, default is 22
#       timeout:  The amount of time before the connection will timeout, default = 10
#       close:    The closed door image for the kindle. This image is directory specific
#                 e.g /mnt/us/does/close.png
#       open:     The open door image for the kindle. This image is directory specific
#                 e.g /mnt/us/does/open.png
environments:
    doorbot1:
        access:
            - full
        loghotdesk: yes
    doorbot2:
        access:
        loghotdesk: no
    doorbot3:
        access:
        kindle:
            ip: 192.168.0.100
            user: root
            password: kindle
            port: 22
            timeout: 10
            close: /mnt/us/does/close.png
            open: /mnt/us/does/open.png
    test:
        access:
        loghotdesk:
        rcapp: rcapp1
# Special sounds that override user ringtones on specific days.
# A random file form the selection will be chosen on the day.
sounds:
# Talk like a pirate day
    "9-19":
        - "parrot/bottle-of-rum.wav"
        - "parrot/pieces-of-eight.wav"
        - "parrot/shiver-me-timbers.wav"
# Halloween
    "10-31":
        - "halloween/cackle3.wav"
        - "halloween/creakdoor2.wav"
        - "halloween/ghost5.wav"
        - "halloween/howling1.wav"
        - "halloween/thunder12.wav"
# A hash of users
# Hash is keyed on the RFID tag's UID
# User entity is a hash containing the following elements:
#   name:       Name of the person, used for logging
#   nickname:   Nickname, currently used when saying hello or goodbye
#   hotdesker:  Boolean, if yes this will submit to a Google
#               Form when the person checks in
#   ringtone:   Filename of a wav file to play when person arrives.
#               Files should be found in wav/ subdirectory
#   access:     An array of access levels, currently only "full" is valid
#   primary:    If this entry is present, the given UID is used instead
users:
    "abababab":
        name: John Appleseed
        nickname: John
    "bcbcbcbc":
        name: John Smith
        nickname: John
        hotdesker: yes
    "cdcdcdcd":
        name: Jane Doe
        nickname: Jane
        ringtone: pursuit-of-vikings.wav
        access:
            full
    "dededede":
        primary: "abababab"